### ISSUE TITLE
Can not go into low power

### ISSUE THREAD

**Issue by jpmeijers** [wuxx/nanoESP32-C6#1]
This board does not have the jumpers to disconnect the 3.3V rail to measure the power usage of the ESP32-C3. This means the RGB-LED and the CH343 are always powered. Due to this the power drawn on the 3.3V rail is 4.88mA in deep sleep.

![Screenshot from 2023-07-25 14-09-04](https://github.com/wuxx/nanoESP32-C6/assets/948278/1d832431-361a-4a39-bef4-90f84ea678ff)

**Comment by wuxx** [comment]
Hello, this development board is used for general functions. If it is necessary to measure low power consumption, you can remove the CH343P and RGB LED, and use the native USB port of ESP32-C6 for downloading.
