### ISSUE TITLE
Using GPIO_SET to use the GPIO dont work

### ISSUE THREAD

**Issue by Sectorchan** [wuxx/nanoESP32-C6#5]
Hi,

Used the ESP-IDF blink sample with the onboard LED on Pin8. Which works like a charm.

Switching from "led_strip_set_pixel" to "gpio_set_level" fails, no LED on PIN8 nor on any other GPIO connected works.

**Comment by webartoli** [comment]
Hi @Sectorchan ,
  I cannot run ESP-IDF blink sample with the onboard LED on Pin8.
  
  My menu config is:

  - Blink Led Type: LED strip
  - Led strip backend peripheral: RMT
  - Blink GPIO number: 8
  - Blink period: 1000

Also tried LED strp with SPI and GPIO blink type.

Maybe some power supply issue ? I'm new in this field
