### ISSUE TITLE
Onboard LED not working

### ISSUE THREAD

**Issue by lukechadwick** [wuxx/nanoESP32-C6#9]
I purchased 10 of these boards.

I've opened 2 and they seem to work properly apart from the onboard LED.  One doesn't work at all and the second only works if I push down hard on it, so maybe a solder joint issue.  I just tried a third and it seems to work okay.

Is this a known issue with these?  A bit disappointing to have 2 faulty out of the 3 I've tried already.

**Comment by wuxx** [comment]
Hello, where did you purchase it from? Each one has been tested before delivery, and the default program is flashing lights

**Comment by lukechadwick** [comment]
Hi I got it from AliExpress and the description has the link to this GitHub
https://a.aliexpress.com/_msEM9cG

**Comment by wuxx** [comment]
This is not our store. What you purchased is a pirated copy of ours.
this is our shop, thanks.
https://miusecntech-muselab.aliexpress.com/store/1101496384

**Comment by lukechadwick** [comment]
Okay I will report them on AliExpress and try your store in the future.  Thank you.

**Comment by lukechadwick** [comment]
Hi @wuxx are you still selling these? I can't find them in the store and the link on github is 404

**Comment by wuxx** [comment]
Hello, can you visit this link?
https://miusecntech-muselab.aliexpress.com/store/1101496384?spm=a2g0o.detail.0.0.58980zS90zS9gu
